---
title: "Mục tiêu 2 - So sánh giữa 2 đợt dịch"
format: html
---

## 1. Import and process data

```{r}
#| warning: false
#| message: false

date_cols <- c("ngay_sinh", "ngay_kp", "ngay_nv", "ngay_bc")

df <- readxl::read_xlsx("data.xlsx", sheet = "data", col_types = "text")

df <- df %>% clean_names()

df[date_cols] <- lapply(df[date_cols], convert_excel_mixed_date)

df <- df %>% mutate(
  across(c(ngay_sinh, ngay_bc, ngay_kp, ngay_nv),
         ~ as.Date(.x, "%d/%m/%Y")))
```

## 2. Epidemic trend

```{r}
ggplot(df %>% filter(!is.na(ngay_nv)), aes(x = ngay_nv)) +
  geom_histogram(binwidth = 30, fill = "steelblue", color = "white") +
  scale_x_date(date_breaks = "3 month", date_labels = "%m/%Y") +
  scale_y_continuous(expand = c(0,0)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

## 3. Process Date Onset 

```{r}
## Outbreak 2018-2019
ob1 <- df %>% filter(ngay_nv>="2018-08-27" & ngay_nv<="2020-04-30") %>%
  mutate(
  ngay_kp = ngay_nv
)


## Outbreak 2024-2025
ob2 <- df %>% filter(ngay_kp>="2024-01-01") %>% 
  mutate(
  diff_nvbc = as.numeric(ngay_bc - ngay_nv), 
  diff_kpnv = as.numeric(ngay_nv - ngay_kp),
  diff_kpbc = as.numeric(ngay_bc - ngay_kp),
  ngay_kp = ngay_nv
  )


## Combine 2 outbreak
df <- bind_rows(ob1[,1:15], ob2[,1:15])

df <- df %>% mutate(
  year = year(ngay_kp),
  week = isoweek(ngay_kp),
  month = month(ngay_kp),
  age_interval = interval(ngay_sinh, ngay_kp),
  age_month = age_interval %/% months(1),
  age_group = case_when(
      age_month < 12 ~ "<1 tuổi",
      age_month <= 60 ~ "1-5 tuổi",     
      age_month <= 120 ~ "6-10 tuổi",
      age_month <= 180 ~ "10-15 tuổi",
      TRUE              ~ ">15 tuổi"
    ),
  age_group = factor(age_group, levels = c("<1 tuổi", "1-5 tuổi", "6-10 tuổi", "10-15 tuổi", ">15 tuổi")),
  gioi = case_when(
    gioi %in% c("nam", "Nam", "NAM") ~ "Nam",
    TRUE ~ "Nữ"
  ),
  pl_chan_doan = case_when(
    pl_chan_doan %in% "Loại trừ sởi" ~ NA,
    pl_chan_doan %in% "Sởi XĐ PTN" ~ "Phòng thí nghiệm",
    pl_chan_doan %in% "Sởi nghi lâm sàng" ~ "Dịch tễ học",
    TRUE ~ "Sởi"
  ),
  bien_chung = case_when(
    bien_chung %in% c("Không", "KHÔNG", "không") ~ "Không",
    is.na(bien_chung) ~ "Không xác định",
    TRUE ~ "Có"
  ),
  tinh_trang = case_when(
    tinh_trang %in% "Điều trị ngoại trú" ~ "Ngoại trú",
    tinh_trang %in% "Điều trị nội trú" ~ "Nội trú",
    TRUE ~ "Khác"
  )
) %>% 
  rename(
    birth = ngay_sinh,
    sex = gioi,
    diagnosis = pl_chan_doan,
    complication = bien_chung,
    status = tinh_trang,
    dates = ngay_kp,
    admission = ngay_nv,
    report = ngay_bc,
    vaccine_status = x0_tiemchung,
    vaccine_episode = x0_lantc
  )

df <- df %>% mutate(
  episode = case_when(
    year(dates) %in% c("2018","2019","2020") ~ 1,
    TRUE ~ 2
  )
)
```

## 4. Esstimate Rt of Ob1

```{r}
ob1_case <- df %>% 
  filter(dates>="2018-09-09" & dates<="2020-03-31") %>% 
  group_by(dates) %>% 
  summarise(I = n())

ob1_case <- ob1_case %>%
    complete(dates = seq(min(dates), max(dates), by = "day")) %>%
    replace_na(list(I = 0))

t_start <- seq(2, nrow(ob1_case)-13)
t_end <- t_start + 13

mod <- estimate_R(
  incid = ob1_case, 
  method = "parametric_si", 
  config = make_config(
    list(
      mean_si = 14.5, # Y văn
      std_si = 3.25, # Y văn
      t_start = t_start,
      t_end = t_end
    )
  )
)

df_rt_ob1 <- process_data(mod)

df_rt_ob1 <- df_rt_ob1 %>% 
     arrange(dates) %>% 
     mutate(id = consecutive_id(pl))
```

### Biểu đồ Rt gộp với số ca của đợt dịch 1

```{r}
start_date <- as.Date("2018-10-01")
end_date   <- as.Date("2020-05-01")

df_rt_ob1$dates <- as.Date(df_rt_ob1$dates)
ob1_case$dates   <- as.Date(ob1_case$dates)

## Scale số ca để vẽ 2 trục y
max_I <- max(ob1_case$I[ob1_case$dates >= start_date & ob1_case$dates <= end_date], na.rm = TRUE)
k <- ifelse(max_I > 0, max_I / 3, 1)


ggplot() +
    geom_col(
        data = ob1_case %>% filter(dates >= start_date & dates <= end_date),
        aes(x = dates, y = I / k),
        fill = "steelblue", alpha = 0.35
    ) +
  geom_line(
        data = df_rt_ob1 %>% filter(dates >= start_date & dates <= end_date),
        aes(x = dates, y = rt),
        color = "darkred", size = 1
    ) +
    geom_ribbon(
        data = df_rt_ob1 %>% filter(dates >= start_date & dates <= end_date),
        aes(x = dates, ymin = q1_rt, ymax = q3_rt),
        fill = "darkred", alpha = 0.18, color = NA
    ) +
    geom_hline(yintercept = 1, linetype = "dashed") +
    scale_y_continuous(
        name = expression(R[t]),
        limits = c(0, 3),
        breaks = seq(0, 3, 0.5),
        expand = c(0,0),
        sec.axis = sec_axis(~ . * k, name = "Số ca")
    ) +
    scale_x_date(
        limits = c(start_date, end_date),
        date_labels = "%b-%Y",
        date_breaks = "1 month",
        name = "Ngày khởi phát"
    ) +
    theme_classic(base_size = 13) +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1)
    )
```

## 5. Estimate Rt of Ob2

```{r}
ob2_case <- df %>% 
  filter(dates>="2024-05-27") %>% 
  group_by(dates) %>% 
  summarise(I = n())

ob2_case <- ob2_case %>%
    complete(dates = seq(min(dates), max(dates), by = "day")) %>%
    replace_na(list(I = 0))

t_start <- seq(2, nrow(ob2_case)-13)
t_end <- t_start + 13

mod <- estimate_R(
  incid = ob2_case, 
  method = "parametric_si", 
  config = make_config(
    list(
      mean_si = 14.5, # Y văn
      std_si = 3.25, # Y văn
      t_start = t_start,
      t_end = t_end
    )
  )
)

df_rt_ob2 <- process_data(mod)

df_rt_ob2 <- df_rt_ob2 %>% 
     arrange(dates) %>% 
     mutate(id = consecutive_id(pl))
```

### Biểu đồ Rt gộp với số ca của đợt dịch 2

```{r}
start_date <- as.Date("2024-07-01")
end_date   <- as.Date("2025-03-31")

df_rt_ob2$dates <- as.Date(df_rt_ob2$dates)
ob2_case$dates   <- as.Date(ob2_case$dates)

## Scale số ca để vẽ 2 trục y
max_I <- max(ob2_case$I[ob2_case$dates >= start_date & ob2_case$dates <= end_date], na.rm = TRUE)
k <- ifelse(max_I > 0, max_I / 3, 1)


ggplot() +
    geom_col(
        data = ob2_case %>% filter(dates >= start_date & dates <= end_date),
        aes(x = dates, y = I / k),
        fill = "steelblue", alpha = 0.35
    ) +
  geom_line(
        data = df_rt_ob2 %>% filter(dates >= start_date & dates <= end_date),
        aes(x = dates, y = rt),
        color = "darkred", size = 1
    ) +
    geom_ribbon(
        data = df_rt_ob2 %>% filter(dates >= start_date & dates <= end_date),
        aes(x = dates, ymin = q1_rt, ymax = q3_rt),
        fill = "darkred", alpha = 0.18, color = NA
    ) +
    geom_hline(yintercept = 1, linetype = "dashed") +
    scale_y_continuous(
        name = expression(R[t]),
        limits = c(0, 3),
        breaks = seq(0, 3, 0.5),
        expand = c(0,0),
        sec.axis = sec_axis(~ . * k, name = "Số ca")
    ) +
    scale_x_date(
        limits = c(start_date, end_date),
        date_labels = "%b-%Y",
        date_breaks = "1 month",
        name = "Ngày khởi phát"
    ) +
    theme_classic(base_size = 13) +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1)
    )
```

## 6. So sánh giữa 2 đợt dịch

### Rt

```{r}
df_rt_ob1$episode <- 1
df_rt_ob2$episode <- 2
df_rt <- bind_rows(df_rt_ob1, df_rt_ob2)

tbl1 <- df_rt %>% 
  mutate(episode = as.factor(episode),
        pl = factor(pl, levels = c("xanh", "vang", "cam", "do", "tim"))) %>% 
  tbl_summary(by=episode, 
              include = c(rt, q1_rt, q3_rt, pl)) %>%
  add_p()
```

### Các chỉ số khác

```{r}
df <- df %>%
  mutate(
    sex = as.factor(sex),
    status = as.factor(status),
    episode = as.factor(episode)
  )

df <- df %>% filter(
  year(birth) != 1905
)

tbl2 <- df %>% 
  tbl_summary(
  by = episode,
  include = c(age_month, age_group, sex, status, vaccine_status,
              vaccine_episode),
  missing = "no",
  statistic = list(
    all_continuous() ~ "{median} ({p25}-{p75})",
    all_categorical() ~ "{n} ({p}%)"
  )
) %>%
  add_p()
```

```{r}
tbl_stack(list(tbl1, tbl2))
```

## 7. Phân tích trong mỗi đợt dịch

### Rt

```{r}
##### Phân tầng theo nhóm tuổi
ob1_rt_agegr <- calc_rt_grouped(df,
                                group_var = age_group,
                                date_range = c("2018-09-09", "2020-03-31"))

tbl1 <- ob1_rt_agegr %>% 
  mutate(group = factor(group, levels = c("<1 tuổi", "1-5 tuổi", "6-10 tuổi", "10-15 tuổi", ">15 tuổi")),
        pl = factor(pl, levels = c("xanh", "vang", "cam", "do", "tim"))) %>% 
  tbl_summary(by=group, 
              include = c(rt, q1_rt, q3_rt, pl),
              missing = "no") %>%
  add_p()

ob2_rt_agegr <- calc_rt_grouped(df,
                                group_var = age_group,
                                date_range = c("2024-05-31", "2025-03-31"))

tbl2 <- ob2_rt_agegr %>% 
  mutate(group = factor(group, levels = c("<1 tuổi", "1-5 tuổi", "6-10 tuổi", "10-15 tuổi", ">15 tuổi")),
        pl = factor(pl, levels = c("xanh", "vang", "cam", "do", "tim"))) %>% 
  tbl_summary(by=group, 
              include = c(rt, q1_rt, q3_rt, pl),
              missing = "no") %>%
  add_p()

tbl_merge(list(tbl1, tbl2), tab_spanner = c("Đợt dịch 1", "Đợt dịch 2"))
```


