---
title: "Mục tiêu 2"
format: 
  docx:
    fig-dpi: 1000
    fig-align: center
    fig-format: svg
    fig-height: 5
    fig-width: 9
execute:
  echo: false
  warning: false
  message: false
---

```{r}
#| warning: false
#| message: false
library(tidyverse)
library(skimr)
library(stringr)
library(lubridate)
library(gtsummary)
library(janitor)
library(EpiEstim)
library(purrr)
library(lubridate)
library(viridis)
library(ggpubr)
library(igraph)
library(ggraph)
library(reshape2)

## Import excel data
convert_excel_mixed_date <- function(x) {
  x <- trimws(x)
  is_num <- suppressWarnings(!is.na(as.numeric(x)))
  
  result <- rep(NA, length(x))
  
  result[is_num] <- as.Date(as.numeric(x[is_num]), origin = "1899-12-30")

  result[!is_num] <- suppressWarnings(dmy(x[!is_num]))

  result <- as.Date(result, origin = "1970-01-01")
  
  return(result)
}


## Calculate pct of Rt
process_data <- function(mod_data) {
  df_rt <- mod_data$R %>%
    mutate(
      dates = mod_data$dates[t_end],
      q1_rt = `Quantile.0.025(R)`,
      q3_rt = `Quantile.0.975(R)`,
      rt = `Mean(R)`,
      b_posterior = `Std(R)`^2 / `Mean(R)`,
      a_posterior = `Mean(R)` / b_posterior,
      pct = pgamma(1, shape = a_posterior, scale = b_posterior, lower.tail = FALSE),
      pl = case_when(
        pct > 0.9 ~ "tim",
        pct > 0.75 & pct <= 0.9 ~ "do",
        pct > 0.25 & pct <= 0.75 ~ "cam",
        pct > 0.1 & pct <= 0.25 ~ "vang",
        pct < 0.1 ~ "xanh"
      )
    )
  
  return(df_rt)
}


## Estimate_R() cho Age Group và Vaccinate


calc_rt_grouped <- function(data, group_var, 
                            date_col = "dates",
                            date_range = c("2018-08-27", "2020-04-30"),
                            mean_si = 14.5, std_si = 3.25) {
  stopifnot(date_col %in% names(data))
  group_var <- rlang::ensym(group_var)
  
  df_filtered <- data %>%
    filter(.data[[date_col]] >= as.Date(date_range[1]),
           .data[[date_col]] <= as.Date(date_range[2]))
  
  df_grouped <- df_filtered %>%
    group_by(!!group_var, .data[[date_col]]) %>%
    summarise(I = n(), .groups = "drop")
  
  df_rt <- df_grouped %>%
    group_split(!!group_var) %>%
    map_dfr(function(x) {
      est <- EpiEstim::estimate_R(
        incid = x$I,
        method = "parametric_si",
        config = make_config(list(
          mean_si = mean_si, std_si = std_si
        ))
      )
      
      Rtab <- est$R %>%
        mutate(
          group = unique(x[[rlang::as_string(group_var)]]),
          dates = x[[date_col]][t_end],
          b_posterior = (`Std(R)`^2) / `Mean(R)`,
          a_posterior = `Mean(R)` / b_posterior,
          pct = pgamma(1, shape = a_posterior, scale = b_posterior, lower.tail = FALSE),
          pl = case_when(
            pct > 0.9 ~ "tim",
            pct > 0.75 & pct <= 0.9 ~ "do",
            pct > 0.25 & pct <= 0.75 ~ "cam",
            pct > 0.1 & pct <= 0.25 ~ "vang",
            pct < 0.1 ~ "xanh"
          )
        ) %>%
        select(group, dates, rt = `Mean(R)`, q1_rt = `Quantile.0.025(R)`,
               q3_rt = `Quantile.0.975(R)`, a_posterior, b_posterior, pct, pl)
      
      return(Rtab)
    })
  
  return(df_rt)
}

# --- Hàm tính cross-correlation ---
get_ccf <- function(x, y, max_lag = 5) {
  ccf_obj <- ccf(x, y, plot = FALSE, lag.max = max_lag)
  tibble(
    lag = ccf_obj$lag,
    correlation = ccf_obj$acf
  )
}
```


## 1. Import and process data

```{r}
#| warning: false
#| message: false

df <- readxl::read_xlsx("data.xlsx",
                        sheet = "data",
                        col_types = "text")

df <- df %>% clean_names()

date_cols <- c("ngay_sinh", "ngay_kp", "ngay_nv", "ngay_bc")

df[date_cols] <- lapply(df[date_cols], convert_excel_mixed_date)
```

## 2. Epidemic trend

```{r}
ggplot(df %>% filter(!is.na(ngay_nv)), aes(x = ngay_nv)) +
  geom_histogram(binwidth = 30, fill = "steelblue", color = "white") +
  scale_x_date(date_breaks = "3 month", date_labels = "%m/%Y") +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Ngày khởi phát",
       y = "Số ca") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, 
                                   hjust = 0.5,
                                   size = 10,
                                   color = "black"),
        axis.text.y = element_text(size = 10,
                                   color = "black"))
```

## 3. Process Date Onset 

```{r}
df <- df %>% mutate(
  age_interval = interval(ngay_sinh, ngay_nv),
  age_month = age_interval %/% months(1),
  age_group = case_when(
      age_month<12 ~ "<1 tuổi",
      age_month>=12 & age_month<=60 ~ "1-5 tuổi",     
      age_month>60 & age_month<=120 ~ "6-10 tuổi",
      age_month>120 & age_month<=180 ~ "11-15 tuổi",
      TRUE ~ ">15 tuổi"
    ),
  age_group = factor(age_group, levels = c("<1 tuổi", "1-5 tuổi", "6-10 tuổi", "11-15 tuổi", ">15 tuổi")),
  gioi = case_when(
    gioi %in% c("nam", "Nam", "NAM") ~ "Nam",
    TRUE ~ "Nữ"
  ),
  pl_chan_doan = case_when(
    pl_chan_doan %in% "Loại trừ sởi" ~ NA,
    pl_chan_doan %in% "Sởi XĐ PTN" ~ "Phòng thí nghiệm",
    pl_chan_doan %in% "Sởi nghi lâm sàng" ~ "Dịch tễ học",
    TRUE ~ "Sởi"
  ),
  bien_chung = case_when(
    bien_chung %in% c("Không", "KHÔNG", "không") ~ "Không",
    is.na(bien_chung) ~ "Không xác định",
    TRUE ~ "Có"
  ),
  status = case_when(
    tinh_trang %in% c("Điều trị nội trú", 
                      "Ra viện",
                      "Chuyển viện") ~ "Nội trú",
    tinh_trang %in% "Điều trị ngoại trú" ~ "Ngoại trú",
    tinh_trang %in% "Tử vong" ~ "Tử vong",
    TRUE ~ tinh_trang
  )) %>% 
  rename(
    birth = ngay_sinh,
    sex = gioi,
    diagnosis = pl_chan_doan,
    complication = bien_chung,
    vaccination = tc,
    dates = ngay_kp,
    admission = ngay_nv,
    report = ngay_bc
  )

df <- df[!(df$admission >= as.Date("2024-01-01") & is.na(df$diagnosis)), ]

df <- df %>% mutate(
  quan_huyen = case_when(
    quan_huyen %in% c("Thủ Đức", "Quận 9", "Quận 2", 
                      "QUẬN 9","THỦ ĐỨC","Quận Thủ Đức" ) ~ "Thành phố Thủ Đức",
    quan_huyen %in% c("BÌNH CHÁNH", "Huyện Bình Chánh") ~ "Bình Chánh",
    quan_huyen %in% c("BÌNH TÂN", "Quận Bình Tân" ) ~ "Bình Tân",
    quan_huyen %in% c("QUẬN 11") ~ "Quận 11",
    quan_huyen %in% c("QUẬN 12") ~ "Quận 12",
    quan_huyen %in% c("QUẬN 10") ~ "Quận 10",
    quan_huyen %in% c("QUẬN 7") ~ "Quận 7",
    quan_huyen %in% c("CỦ CHI", "Huyện Củ Chi") ~ "Củ Chi",
    quan_huyen %in% c("GÒ VẤP", "Quận Gò vấp","Gò vấp") ~ "Gò Vấp",
    quan_huyen %in% c("HÓC MÔN", "Huyện Hóc Môn") ~ "Hóc Môn",
    quan_huyen %in% c("QUẬN 3") ~ "Quận 3",
    quan_huyen %in% c("QUẬN 7") ~ "Quận 7",
    quan_huyen %in% c("TÂN BÌNH", "Quận Tân Bình") ~ "Tân Bình",
    quan_huyen %in% c("TÂN PHÚ","Quận Tân Phú") ~ "Tân Phú",
    quan_huyen %in% c("Quận Bình Thạnh",  "BÌNH THẠNH" ) ~ "Bình Thạnh",
    quan_huyen %in% c( "Quận Phú Nhuận","PHÚ NHUẬN"  ) ~ "Phú Nhuận",
    quan_huyen %in% c( "Huyện Nhà Bè", "NHÀ BÈ" ) ~ "Nhà Bè",
    quan_huyen %in% c( "QUẬN 6") ~ "Quận 6",
    quan_huyen %in% c( "Huyện Cần Giờ") ~ "Cần Giờ",
    quan_huyen %in% c( "QUẬN 1" ) ~ "Quận 1",
    TRUE ~ quan_huyen
  ))

#Danh sách các ca thuộc 22 QH
qh_list <- c(
  "Quận 1", "Quận 3", "Quận 4", "Quận 5", "Quận 6", 
  "Quận 7", "Quận 8", "Quận 10", "Quận 11", "Quận 12",
  "Bình Thạnh", "Gò Vấp", "Phú Nhuận", "Tân Bình", 
  "Tân Phú", "Bình Tân","Thành phố Thủ Đức","Bình Chánh",
  "Hóc Môn", "Củ Chi", "Nhà Bè", "Cần Giờ")
  
df <- df %>%
  filter(quan_huyen %in% qh_list)

df <- distinct(df)

df <- df %>% mutate(
  dates = admission,
  episode = case_when(
    year(dates) %in% c("2018","2019","2020") ~ 1,
    TRUE ~ 2
  )
)

df <- df %>% filter(
  age_month < 1200
)
```

## 4. Esstimate Rt of Ob1

```{r}
ob1_case <- df %>% 
  filter(dates>="2018-01-01" & dates<="2020-03-31") %>%
  group_by(dates) %>% 
  summarise(I = n())

ob1_rt <- df %>% 
  filter(dates>="2018-08-27" & dates<="2020-03-31") %>% 
  # 27/08/2018 là ngày bắt đầu, trong 14 ngày có đủ 12 ca
  group_by(dates) %>% 
  summarise(I = n())

ob1_rt <- ob1_rt %>%
    complete(dates = seq(min(dates), max(dates), by = "day")) %>%
    replace_na(list(I = 0))

t_start <- seq(2, nrow(ob1_rt)-13)
t_end <- t_start + 13

mod <- estimate_R(
  incid = ob1_rt, 
  method = "parametric_si", 
  config = make_config(
    list(
      mean_si = 14.5, # Y văn
      std_si = 3.25, # Y văn
      t_start = t_start,
      t_end = t_end
    )
  )
)

df_rt_ob1 <- process_data(mod)

df_rt_ob1 <- df_rt_ob1 %>% 
     arrange(dates) %>% 
     mutate(id = consecutive_id(pl))
```

### Biểu đồ Rt gộp với số ca của đợt dịch 1

```{r}
start_date <- as.Date("2018-01-01")
end_date   <- as.Date("2020-03-31")

df_rt_ob1$dates <- as.Date(df_rt_ob1$dates)
ob1_case$dates   <- as.Date(ob1_case$dates)

## Scale số ca để vẽ 2 trục y
max_I <- max(ob1_case$I[ob1_case$dates >= start_date & ob1_case$dates <= end_date], na.rm = TRUE)
k <- ifelse(max_I > 0, max_I / 3, 1)


ggplot() +
    geom_col(
        data = ob1_case %>% filter(dates >= start_date & dates <= end_date),
        aes(x = dates, y = I / k),
        fill = "steelblue", alpha = 0.35
    ) +
  geom_line(
        data = df_rt_ob1 %>% filter(dates >= start_date & dates <= end_date),
        aes(x = dates, y = rt),
        color = "darkred", size = 1
    ) +
    geom_ribbon(
        data = df_rt_ob1 %>% filter(dates >= start_date & dates <= end_date),
        aes(x = dates, ymin = q1_rt, ymax = q3_rt),
        fill = "darkred", alpha = 0.18, color = NA
    ) +
    geom_hline(yintercept = 1, linetype = "dashed") +
    scale_y_continuous(
        name = expression(R[t]),
        limits = c(0, 3),
        breaks = seq(0, 3, 0.5),
        expand = c(0,0),
        sec.axis = sec_axis(~ . * k, name = "Số ca")
    ) +
    scale_x_date(
        limits = c(start_date, end_date),
        date_labels = "%m/%Y",
        date_breaks = "3 month",
        name = "Ngày khởi phát"
    ) +
    theme_classic(base_size = 13) +
    theme(
        axis.text.x = element_text(angle = 45, 
                                   hjust = 1,
                                   size = 12,
                                   color = "black"),
        axis.text.y = element_text(size = 12,
                                   color = "black")
    )
```

## 5. Estimate Rt of Ob2

```{r}
ob2_case <- df %>% 
  filter(dates>="2024-05-28") %>%
  group_by(dates) %>% 
  summarise(I = n())

ob2_rt <- df %>% 
  filter(dates>="2024-05-28") %>% 
  group_by(dates) %>% 
  summarise(I = n())

ob2_rt <- ob2_rt %>%
    complete(dates = seq(min(dates), max(dates), by = "day")) %>%
    replace_na(list(I = 0))

t_start <- seq(2, nrow(ob2_rt)-13)
t_end <- t_start + 13

mod <- estimate_R(
  incid = ob2_rt, 
  method = "parametric_si", 
  config = make_config(
    list(
      mean_si = 14.5, # Y văn
      std_si = 3.25, # Y văn
      t_start = t_start,
      t_end = t_end
    )
  )
)

df_rt_ob2 <- process_data(mod)

df_rt_ob2 <- df_rt_ob2 %>% 
     arrange(dates) %>% 
     mutate(id = consecutive_id(pl))
```

### Biểu đồ Rt gộp với số ca của đợt dịch 2

```{r}
start_date <- as.Date("2024-05-28")
end_date   <- as.Date("2025-03-31")

df_rt_ob2$dates <- as.Date(df_rt_ob2$dates)
ob2_case$dates   <- as.Date(ob2_case$dates)

## Scale số ca để vẽ 2 trục y
max_I <- max(ob2_case$I[ob2_case$dates >= start_date & ob2_case$dates <= end_date], na.rm = TRUE)
k <- ifelse(max_I > 0, max_I / 3, 1)


ggplot() +
    geom_col(
        data = ob2_case %>% filter(dates >= start_date & dates <= end_date),
        aes(x = dates, y = I / k),
        fill = "steelblue", alpha = 0.35
    ) +
  geom_line(
        data = df_rt_ob2 %>% filter(dates >= start_date & dates <= end_date),
        aes(x = dates, y = rt),
        color = "darkred", size = 1
    ) +
    geom_ribbon(
        data = df_rt_ob2 %>% filter(dates >= start_date & dates <= end_date),
        aes(x = dates, ymin = q1_rt, ymax = q3_rt),
        fill = "darkred", alpha = 0.18, color = NA
    ) +
    geom_hline(yintercept = 1, linetype = "dashed") +
    scale_y_continuous(
        name = expression(R[t]),
        limits = c(0, 3),
        breaks = seq(0, 3, 0.5),
        expand = c(0,0),
        sec.axis = sec_axis(~ . * k, name = "Số ca")
    ) +
    scale_x_date(
        limits = c(start_date, end_date),
        date_labels = "%b-%Y",
        date_breaks = "1 month",
        name = "Ngày khởi phát"
    ) +
    theme_classic(base_size = 13) +
    theme(
        axis.text.x = element_text(angle = 45, 
                                   hjust = 1,
                                   size = 12,
                                   color = "black"),
        axis.text.y = element_text(size = 12,
                                   color = "black")
    )
```

## 6. So sánh giữa 2 đợt dịch

### Rt

```{r}
df_rt_ob1$episode <- 1
df_rt_ob2$episode <- 2
df_rt <- bind_rows(df_rt_ob1, df_rt_ob2)

df_rt %>%
  mutate(episode = as.factor(episode),
         pl = factor(pl, levels = c("xanh", "vang", "cam", "do", "tim"))) %>%
  tbl_summary(
    by = episode,
    include = c(rt, q1_rt, q3_rt, pl),
    digits = list(all_categorical() ~ 1)
  ) %>%
  add_p()
```

### Các chỉ số khác

```{r}
#| fig-height: 8
#| fig-width: 10
#| 
df <- df %>%
  mutate(
    sex = as.factor(sex),
    status = as.factor(status),
    episode = as.factor(episode),
    vaccination = as.factor(vaccination)
  )

df %>% 
  filter(
    (dates >= "2018-08-27" & dates <= "2020-03-31") | 
    (dates >= "2024-05-28")
  ) %>% 
  tbl_summary(
  by = episode,
  include = c(age_month, age_group, sex, 
              status, vaccination),
  digits = list(all_categorical() ~ 1),
  statistic = list(
    all_continuous() ~ "{median} ({p25}-{p75})",
    all_categorical() ~ "{n} ({p}%)"
  )
) %>%
  add_p()

pop <- readxl::read_xlsx("pop.xlsx")

cases_summary <- df %>%
  filter(!(dates>="2020-04-01" & dates<="2023-12-31")) %>% 
  group_by(quan_huyen, episode) %>%
  summarise(cases = n(), .groups = "drop") %>%
  left_join(pop, by = "quan_huyen") %>%
  mutate(population = case_when(
    episode == 1 ~ pop_2019,
    episode == 2 ~ pop_2024,
    TRUE ~ NA_real_
  ),
  rate_per_100k = (cases / population) * 100000)

cases_summary_total <- cases_summary %>%
  group_by(episode) %>%
  summarise(
    quan_huyen = "Toàn thành phố",
    cases = sum(cases, na.rm = TRUE),
    pop_2019 = sum(pop_2019, na.rm = TRUE),
    pop_2024 = sum(pop_2024, na.rm = TRUE),
    population = sum(population, na.rm = TRUE),
    rate_per_100k = (cases / population) * 100000,
    .groups = "drop"
  )

cases_summary_final <- bind_rows(cases_summary, cases_summary_total)

ggplot(cases_summary,
       aes(y = reorder(quan_huyen, rate_per_100k),
           x = rate_per_100k,
           fill = factor(episode))) +
    geom_col(position = position_dodge(width = 0.8), width = 0.7) +
    geom_text(aes(label = round(rate_per_100k, 1)),
              position = position_dodge(width = 0.8),
              hjust = -0.2, size = 3.3) +
    scale_fill_manual(
        values = c("1" = "#FB6A4A", "2" = "#00C0C7"),
        labels = c("2018-2019", "2024-2025"),
        name = ""
    )+
    labs(
        x = "Số ca trên 100.000 dân",
        y = "",
        caption = "(p > 0.05)"
    ) +
    scale_x_continuous(expand = c(0,0),
                       limits = c(0,180),
                       breaks = seq(0,180,30)) +
    theme_bw(base_size = 13) +
    theme(
        legend.position = "bottom",
        strip.text = element_text(face = "bold"),
        axis.text.y = element_text(size = 12,
                                   color = "black"),
        axis.text.x = element_text(size = 12,
                                   color = "black")
    ) +
    coord_cartesian(clip = "off") 
```

```{r}
cols_ep <- c("1" = "#9370DB",
             "2" = "#FFD166") 

ggplot(df, aes(x = age_group, fill = factor(episode))) +
  geom_density(alpha = 0.6, position = "identity") +
  scale_fill_manual(values = cols_ep,
                    labels = c("2018-2020", "2024-2025"),
                    name = "") +
  labs(x = "Nhóm tuổi", y = "Density") +
  theme_bw() +
  theme(legend.position = "bottom",
        axis.text.x = element_text(size = 12,
                                   color = "black"),
        axis.text.y = element_text(size = 12,
                                   color = "black"))
```

## 7. Phân tích trong mỗi đợt dịch

### Đợt dịch 2018-2019

```{r}
df %>% filter(dates>="2018-08-27"&dates<="2020-03-31") %>% 
  tbl_summary(by = age_group,
              missing = "no",
              include = c(sex, status, vaccination),
              digits = list(all_categorical() ~ 1),
              statistic = list(
    all_continuous() ~ "{median} ({p25}-{p75})",
    all_categorical() ~ "{n} ({p}%)")) %>% 
  add_overall() %>% 
  add_p()

df %>% filter(episode==1) %>% 
  tbl_summary(by = vaccination,
              include = c(sex, status,
                          age_month, age_group),
              statistic = list(
    all_continuous() ~ "{median} ({p25}-{p75})",
    all_categorical() ~ "{n} ({p}%)")) %>% 
  add_overall() %>% 
  add_p()
```

### Đợt dịch 20224-2025

```{r}
df %>% filter(dates>="2024-05-27") %>% 
  tbl_summary(by = age_group,
              missing = "no",
              include = c(sex, status, vaccination),
              digits = list(all_categorical() ~ 1),
              statistic = list(
    all_continuous() ~ "{median} ({p25}-{p75})",
    all_categorical() ~ "{n} ({p}%)")) %>% 
  add_overall() %>% 
  add_p()

df %>% filter(episode==2) %>% 
  tbl_summary(by = vaccination,
              include = c(sex, status,
                          age_month, age_group),
              statistic = list(
    all_continuous() ~ "{median} ({p25}-{p75})",
    all_categorical() ~ "{n} ({p}%)")) %>% 
  add_overall() %>% 
  add_p()
```

## 8. Vẽ Rt theo màu CDC

```{r}
plot_rt <- function(data) {
  df_plot <- data
  
  df_plot <- head(do.call(rbind, by(df_plot, df_plot$id, rbind, NA)), -1)
  
  df_plot[, c("pl", "id")] <- lapply(df_plot[, c("pl", "id")], zoo::na.locf)
  
  df_plot[] <- lapply(df_plot, zoo::na.locf, fromLast = TRUE)
  
  col <- c("#f26522", "#ed1d24", "#7f3f98", "#ffde17", "#00a14b")
  
  df_plot$color <- col[as.factor(df_plot$pl)]
  
  df_plot <- df_plot %>%
    group_by(id) %>%
    mutate(
      q1_rt_adjusted = q1_rt + (row_number() - 1) * 0.0001,
      q3_rt_adjusted = q3_rt + (row_number() - 1) * 0.0001
    ) %>%
    ungroup()
  
  p <- ggplot(df_plot, aes(x = dates)) +
    
    geom_ribbon(
      aes(
        ymin = q1_rt_adjusted,
        ymax = q3_rt_adjusted,
        fill = factor(pl),
        group = interaction(id, pl)
      ),
      alpha = 0.45
    ) +
    
    geom_line(aes(
      y = rt,
      color = factor(pl),
      group = id
    ), size = 1) +
    
    geom_hline(yintercept = 1,
               linetype = "dashed",
               color = "black") +
    
    geom_vline(
      xintercept = as.Date("2024-09-16"),
      color = "black",
      size = 1
    ) +
    geom_vline(
      xintercept = as.Date("2024-08-31"),
      color = "black",
      size = 1
    ) +
    scale_fill_manual(values = col, name = "Phase (pl)") +
    scale_color_manual(values = col, name = "Phase (pl)") +
    labs(x = "Date", y = "Estimated Rt") +
    theme_bw(base_size = 13) +
    theme(
      panel.grid.minor = element_blank(),
      panel.grid.major.x = element_line(linetype = "dotted"),
      legend.position = "bottom",
      legend.title = element_text(size = 10),
      plot.background = element_rect(fill = "white", color = NA)
    )
  
  return(p)
}

plot_hist <- function(df_filter_plot) {
  ggplot(df_filter_plot, aes(x = dates)) +
    geom_col(aes(y = I), fill = "#87A2FF", width = 0.8) +
    labs(y = "Incidence", x = "") +
    theme_bw(base_size = 12) +
    theme(
      axis.text.x = element_text(angle = 60, hjust = 1),
      panel.grid.minor = element_blank(),
      legend.position = "none",
      plot.background = element_rect(fill = "white", color = NA)
    )
}
```

```{r}
p_hist1 <- ob1_case %>% 
  filter(dates>="2018-10-12") %>% 
  plot_hist()

p_hist2 <- ob2_case %>% 
  filter(dates >= "2024-07-12") %>% 
  plot_hist()

p_rt1 <- df_rt_ob1 %>% 
  filter(dates>="2018-10-12") %>% 
  plot_rt()

p_rt2 <- df_rt_ob2 %>% 
  filter(dates >= "2024-07-12") %>% 
  plot_rt()

(p_hist1|p_rt1) + (p_hist2|p_rt2)
```

## 9. Tương quan số ca quận/huyện

```{r}
df_cor <- df %>% 
  filter(dates >= "2018-08-27" & dates <= "2020-03-31") %>%
  group_by(dates, quan_huyen) %>% 
  summarise(n = n(), .groups = "drop") %>%
  pivot_wider(names_from = quan_huyen, values_from = n, values_fill = 0)

cor_mat <- cor(df_cor %>% select(-dates), use = "pairwise.complete.obs", method = "spearman")

cor_long <- melt(cor_mat)

ccf_df <- get_ccf(df_cor$`Bình Chánh`, df_cor$`Bình Tân`)

p1 <- ggplot(ccf_df, aes(x = lag, y = correlation)) +
  geom_col(fill = "lightblue") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "gray40") +
  labs(x = "Độ trễ",
       y = "Hệ số tương quan",
       title = "Bình Chánh và Bình Tân") +
  scale_x_continuous(breaks = seq(-5,5,1)) + 
  theme_classic()

p2 <- ggplot(cor_long, aes(Var1, Var2, fill = value)) +
  geom_tile(color = "white") +
  geom_point(data = subset(cor_long, abs(value) > 0.7), shape = 21, size = 2, color = "black") +
  scale_fill_gradient2(
  low = "#4575B4", mid = "white", high = "red",
  midpoint = 0, limits = c(-1, 1), name = "Correlation"
)  +
  theme_minimal(base_size = 11) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 8, color = "black"),
    axis.text.y = element_text(size = 8,
                               color = "black"),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    legend.position = "bottom"
  )

cor_network <- cor_mat
cor_network[abs(cor_network) < 0.6] <- 0 

g <- graph_from_adjacency_matrix(cor_network, mode = "undirected", weighted = TRUE, diag = FALSE)

p3 <- ggraph(g, layout = "fr") +
  geom_edge_link(
    aes(width = abs(weight)),
    color = "red",
    alpha = 0.6,
    show.legend = TRUE
  ) +
  scale_edge_width_continuous(
    name = "Correlation"
  ) +
  geom_node_point(size = 5, color = "skyblue") +
  geom_node_text(aes(label = name), repel = TRUE, size = 3) +
  theme_void() +
  guides(
    edge_color = "none" 
  ) + 
  theme(legend.position = "top")

p1 <- p1 +
  coord_cartesian(clip = "off") +
  theme(axis.title.x = element_text(vjust = -0.5))

final_plot <- p2 + (p3 / p1) +
  plot_annotation(
    tag_levels = 'A', 
    tag_prefix = "(",
    tag_suffix = ")"
  ) &
  theme(
    plot.tag = element_text(face = "bold", size = 14)
  )
```

```{r}
df_cor <- df %>% 
  filter(dates >= "2024-05-28") %>%
  group_by(dates, quan_huyen) %>% 
  summarise(n = n(), .groups = "drop") %>%
  pivot_wider(names_from = quan_huyen, values_from = n, values_fill = 0)

cor_mat <- cor(df_cor %>% select(-dates), use = "pairwise.complete.obs")

cor_long <- melt(cor_mat)

ccf_df1 <- get_ccf(df_cor$`Thành phố Thủ Đức`, df_cor$`Tân Bình`)
ccf_df2 <- get_ccf(df_cor$`Thành phố Thủ Đức`, df_cor$`Quận 7`)
ccf_df3 <- get_ccf(df_cor$`Thành phố Thủ Đức`, df_cor$`Quận 8`)
ccf_df4 <- get_ccf(df_cor$`Thành phố Thủ Đức`, df_cor$`Hóc Môn`)

p1 <- ggplot(ccf_df1, aes(x = lag, y = correlation)) +
  geom_col(fill = "lightblue") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "gray40") +
  labs(x = "Độ trễ",
       y = "Hệ số tương quan",
       title = "Thành phố Thủ Đức và Tân Bình") +
  scale_x_continuous(breaks = seq(-5,5,1)) + 
  theme_classic()

p4 <- ggplot(ccf_df2, aes(x = lag, y = correlation)) +
  geom_col(fill = "lightblue") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "gray40") +
  labs(x = "Độ trễ",
       y = "Hệ số tương quan",
       title = "Thành phố Thủ Đức và Quận 7") +
  scale_x_continuous(breaks = seq(-5,5,1)) + 
  theme_classic()

p5 <- ggplot(ccf_df3, aes(x = lag, y = correlation)) +
  geom_col(fill = "lightblue") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "gray40") +
  labs(x = "Độ trễ",
       y = "Hệ số tương quan",
       title = "Thành phố Thủ Đức và Quận 8") +
  scale_x_continuous(breaks = seq(-5,5,1)) + 
  theme_classic()

p6 <- ggplot(ccf_df4, aes(x = lag, y = correlation)) +
  geom_col(fill = "lightblue") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "gray40") +
  labs(x = "Độ trễ",
       y = "Hệ số tương quan",
       title = "Thành phố Thủ Đức và Hóc Môn") +
  scale_x_continuous(breaks = seq(-5,5,1)) + 
  theme_classic()

p2 <- ggplot(cor_long, aes(Var1, Var2, fill = value)) +
  geom_tile(color = "white") +
  geom_point(data = subset(cor_long, abs(value) > 0.7), shape = 21, size = 2, color = "black") +
  scale_fill_gradient2(
  low = "#4575B4", mid = "white", high = "red",
  midpoint = 0, limits = c(-1, 1), name = "Correlation"
)  +
  theme_minimal(base_size = 11) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 8, color = "black"),
    axis.text.y = element_text(size = 8,
                               color = "black"),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    legend.position = "bottom"
  )

cor_network <- cor_mat
cor_network[abs(cor_network) < 0.6] <- 0 

g <- graph_from_adjacency_matrix(cor_network, mode = "undirected", weighted = TRUE, diag = FALSE)

p3 <- ggraph(g, layout = "fr") +
  geom_edge_link(
    aes(width = abs(weight)),
    color = "red",
    alpha = 0.6,
    show.legend = TRUE
  ) +
  scale_edge_width_continuous(
    name = "Correlation"
  ) +
  geom_node_point(size = 5, color = "skyblue") +
  geom_node_text(aes(label = name), repel = TRUE, size = 3) +
  theme_void() +
  guides(
    edge_color = "none" 
  ) + 
  theme(legend.position = "top")

row2 <- wrap_plots(p1, p4, p5, p6, ncol = 4)

final_plot <- (p2 + p3) / row2 +
  plot_annotation(
    tag_levels = 'A',
    tag_prefix = "(",
    tag_suffix = ")"
  )

ggsave("combined_plot.png", final_plot, width = 16, height = 10, dpi = 800)
```


